export const STRINGS = {
  AUTH: {
    LOGIN_TITLE: 'Sign In',
    LOGIN_SUBTITLE: 'Enter your credentials to access your account',
    USERNAME_LABEL: 'Username',
    PASSWORD_LABEL: 'Password',
    LOGIN_BUTTON: 'Sign In',
    LOGGING_IN: 'Signing in...',
    INVALID_CREDENTIALS: 'Invalid username or password',
    LOGIN_SUCCESS: 'Login successful',
    COOKIE_TOKEN_KEY : 'auth_token'
  },
  NAVIGATION: {
    DASHBOARD: 'Dashboard',
    PRODUCTS: 'Products',
    CATEGORIES: 'Categories',
    THEMES: 'Themes',
    KEYWORDS: 'Keywords',
    BRANDS: 'Brands',
    ORDERS: 'Orders',
    QUOTES: 'Quotes',
    SUPPLIERS: 'Suppliers',
    CUSTOMERS: 'Customers',
    BLOG: 'Blog',
    SEARCHES: 'Searches',
    SITEMAPS: 'Sitemaps',
    FAQ: 'FAQ',
  },
  COMMON: {
    LOADING: 'Loading...',
    ERROR: 'Something went wrong',
    SUCCESS: 'Operation successful',
    LOGOUT: 'Logout',
    MENU: 'Menu',
    CLOSE: 'Close',
    WELCOME: 'Welcome',
  },
  DASHBOARD: {
    TITLE: 'Dashboard',
    WELCOME_MESSAGE: 'Welcome back! Here\'s what\'s happening with your business today.',
  },
} as const;